name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        image_uri=public.ecr.aws/f9o2h2p4/eks-deployment:${{ github.sha }}
        docker build -t $image_uri .
        echo "IMAGE_URI=$image_uri" >> $GITHUB_ENV

    - name: Push Docker Image to ECR
      run: |
        docker push $IMAGE_URI

    - name: Replace TAG in Deployment YAML
      run: |
        sed -i "s|{{TAG}}|${{ github.sha }}|g" deployment.yaml

    - name: Apply Kubernetes Deployment
      uses: azure/k8s-set-context@v3
      with:
        namespace: default
        # Add Kubernetes secrets or config if required

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
